language:
    python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "virtualenv venv"
  - ". venv/bin/activate"
# command to run tests
script:
  - python -m "nose" --with-cov --cov . --with-timer tests/*
notifications:
    email: false
