language:
    python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install virtualenv"
  - "python -m \"virtualenv\" venv"
  - ". venv/bin/activate"
  - "pip install -r requirements.txt"
  - "coverage --version"
# command to run tests
script:
  - python -m "nose" --with-coverage --cov PittAPI/ --with-timer tests/*
notifications:
    email: false
os:
  - linux
