language:
    python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
    "pip install -r requirements.txt"
# command to run tests
script:
  - python tests/test_course.py
  - python tests/test_dining.py
  - python tests/test_shuttle.py
notifications:
    email: false
